# Generated by Django 5.0.4 on 2024-07-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('ratingBefore', models.IntegerField()),
                ('ratingAfter', models.IntegerField()),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
