# Generated by Django 5.0.6 on 2024-07-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalambury_app', '0002_alter_feedback_gender_alter_feedback_ratingafter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
